regels = [
    "Is this the real life? Is this just fantasy?",
    "Caught in a landslide, no escape from reality",
    "Open your eyes, look up to the skies and see",
    "I'm just a poor boy, I need no sympathy",
    "Because I'm easy come, easy go, little high, little low",
    "Any way the wind blows doesn't really matter to me, to me",
    "Too late, my time has come",
    "Sends shivers down my spine, body's aching all the time",
    "Goodbye, everybody, I've got to go",
    "Gotta leave you all behind and face the truth",
    "Mama, ooh (Any way the wind blows)",
    "I don't wanna die",
    "I sometimes wish I'd never been born at all",
    "I see a little silhouetto of a man",
    "Scaramouche, Scaramouche, will you do the Fandango?",
    "Thunderbolt and lightning, very, very frightening me",
    "Nothing really matters, anyone can see",
    "Nothing really matters",
    "Nothing really matters to me",
    "Any way the wind blows",
    "He's just a poor boy from a poor family",
]


